In [2]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

SEED = 41
np.random.seed(SEED)

In [6]:
!ls ../data/01_raw

DataDictionaryWiDS2021.csv   TrainingWiDS2021.csv
SampleSubmissionWiDS2021.csv UnlabeledWiDS2021.csv
SolutionTemplateWiDS2021.csv

In [12]:
%%time
train = pd.read_csv('../data/01_raw/TrainingWiDS2021.csv')
test  = pd.read_csv('../data/01_raw/UnlabeledWiDS2021.csv')

CPU times: user 1.62 s, sys: 217 ms, total: 1.84 s
Wall time: 1.84 s

In [11]:
train.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130157 entries, 0 to 130156
Data columns (total 181 columns):
 #    Column                       Non-Null Count   Dtype
---   ------                       --------------   -----
 0    Unnamed: 0                   130157 non-null  int64
 1    encounter_id                 130157 non-null  int64
 2    hospital_id                  130157 non-null  int64
 3    age                          125169 non-null  float64
 4    bmi                          125667 non-null  float64
 5    elective_surgery             130157 non-null  int64
 6    ethnicity                    128570 non-null  object
 7    gender                       130091 non-null  object
 8    height                       128080 non-null  float64
 9    hospital_admit_source        96959 non-null   object
 10   icu_admit_source             129917 non-null  object
 11   icu_id                       130157 non-null  int64
 12   icu_stay_type                130157 non-null  object
 13   icu_type                     130157 non-null  object
 14   pre_icu_los_days             130157 non-null  float64
 15   readmission_status           130157 non-null  int64
 16   weight                       126694 non-null  float64
 17   albumin_apache               51994 non-null   float64
 18   apache_2_diagnosis           128472 non-null  float64
 19   apache_3j_diagnosis          129292 non-null  float64
 20   apache_post_operative        130157 non-null  int64
 21   arf_apache                   130157 non-null  int64
 22   bilirubin_apache             47597 non-null   float64
 23   bun_apache                   104746 non-null  float64
 24   creatinine_apache            105275 non-null  float64
 25   fio2_apache                  30437 non-null   float64
 26   gcs_eyes_apache              127967 non-null  float64
 27   gcs_motor_apache             127967 non-null  float64
 28   gcs_unable_apache            129448 non-null  float64
 29   gcs_verbal_apache            127967 non-null  float64
 30   glucose_apache               115461 non-null  float64
 31   heart_rate_apache            129848 non-null  float64
 32   hematocrit_apache            103399 non-null  float64
 33   intubated_apache             130157 non-null  int64
 34   map_apache                   129737 non-null  float64
 35   paco2_apache                 30437 non-null   float64
 36   paco2_for_ph_apache          30437 non-null   float64
 37   pao2_apache                  30437 non-null   float64
 38   ph_apache                    30437 non-null   float64
 39   resprate_apache              129349 non-null  float64
 40   sodium_apache                105638 non-null  float64
 41   temp_apache                  123546 non-null  float64
 42   urineoutput_apache           66990 non-null   float64
 43   ventilated_apache            130157 non-null  int64
 44   wbc_apache                   100682 non-null  float64
 45   d1_diasbp_invasive_max       35089 non-null   float64
 46   d1_diasbp_invasive_min       35089 non-null   float64
 47   d1_diasbp_max                129880 non-null  float64
 48   d1_diasbp_min                129880 non-null  float64
 49   d1_diasbp_noninvasive_max    128521 non-null  float64
 50   d1_diasbp_noninvasive_min    128521 non-null  float64
 51   d1_heartrate_max             129895 non-null  float64
 52   d1_heartrate_min             129895 non-null  float64
 53   d1_mbp_invasive_max          35289 non-null   float64
 54   d1_mbp_invasive_min          35289 non-null   float64
 55   d1_mbp_max                   129830 non-null  float64
 56   d1_mbp_min                   129830 non-null  float64
 57   d1_mbp_noninvasive_max       127929 non-null  float64
 58   d1_mbp_noninvasive_min       127929 non-null  float64
 59   d1_resprate_max              129474 non-null  float64
 60   d1_resprate_min              129474 non-null  float64
 61   d1_spo2_max                  129625 non-null  float64
 62   d1_spo2_min                  129625 non-null  float64
 63   d1_sysbp_invasive_max        35119 non-null   float64
 64   d1_sysbp_invasive_min        35119 non-null   float64
 65   d1_sysbp_max                 129886 non-null  float64
 66   d1_sysbp_min                 129886 non-null  float64
 67   d1_sysbp_noninvasive_max     128534 non-null  float64
 68   d1_sysbp_noninvasive_min     128534 non-null  float64
 69   d1_temp_max                  125663 non-null  float64
 70   d1_temp_min                  125663 non-null  float64
 71   h1_diasbp_invasive_max       25328 non-null   float64
 72   h1_diasbp_invasive_min       25328 non-null   float64
 73   h1_diasbp_max                124630 non-null  float64
 74   h1_diasbp_min                124630 non-null  float64
 75   h1_diasbp_noninvasive_max    118818 non-null  float64
 76   h1_diasbp_noninvasive_min    118818 non-null  float64
 77   h1_heartrate_max             126083 non-null  float64
 78   h1_heartrate_min             126083 non-null  float64
 79   h1_mbp_invasive_max          25391 non-null   float64
 80   h1_mbp_invasive_min          25391 non-null   float64
 81   h1_mbp_max                   123627 non-null  float64
 82   h1_mbp_min                   123627 non-null  float64
 83   h1_mbp_noninvasive_max       116860 non-null  float64
 84   h1_mbp_noninvasive_min       116860 non-null  float64
 85   h1_resprate_max              123703 non-null  float64
 86   h1_resprate_min              123703 non-null  float64
 87   h1_spo2_max                  123915 non-null  float64
 88   h1_spo2_min                  123915 non-null  float64
 89   h1_sysbp_invasive_max        25350 non-null   float64
 90   h1_sysbp_invasive_min        25350 non-null   float64
 91   h1_sysbp_max                 124638 non-null  float64
 92   h1_sysbp_min                 124638 non-null  float64
 93   h1_sysbp_noninvasive_max     118827 non-null  float64
 94   h1_sysbp_noninvasive_min     118827 non-null  float64
 95   h1_temp_max                  100454 non-null  float64
 96   h1_temp_min                  100454 non-null  float64
 97   d1_albumin_max               58751 non-null   float64
 98   d1_albumin_min               58751 non-null   float64
 99   d1_bilirubin_max             53422 non-null   float64
 100  d1_bilirubin_min             53422 non-null   float64
 101  d1_bun_max                   116423 non-null  float64
 102  d1_bun_min                   116423 non-null  float64
 103  d1_calcium_max               113465 non-null  float64
 104  d1_calcium_min               113465 non-null  float64
 105  d1_creatinine_max            116884 non-null  float64
 106  d1_creatinine_min            116884 non-null  float64
 107  d1_glucose_max               121914 non-null  float64
 108  d1_glucose_min               121914 non-null  float64
 109  d1_hco3_max                  110110 non-null  float64
 110  d1_hco3_min                  110110 non-null  float64
 111  d1_hemaglobin_max            113925 non-null  float64
 112  d1_hemaglobin_min            113925 non-null  float64
 113  d1_hematocrit_max            114569 non-null  float64
 114  d1_hematocrit_min            114569 non-null  float64
 115  d1_inr_max                   48944 non-null   float64
 116  d1_inr_min                   48944 non-null   float64
 117  d1_lactate_max               34654 non-null   float64
 118  d1_lactate_min               34654 non-null   float64
 119  d1_platelets_max             111600 non-null  float64
 120  d1_platelets_min             111600 non-null  float64
 121  d1_potassium_max             117611 non-null  float64
 122  d1_potassium_min             117611 non-null  float64
 123  d1_sodium_max                116887 non-null  float64
 124  d1_sodium_min                116887 non-null  float64
 125  d1_wbc_max                   112728 non-null  float64
 126  d1_wbc_min                   112728 non-null  float64
 127  h1_albumin_max               11152 non-null   float64
 128  h1_albumin_min               11152 non-null   float64
 129  h1_bilirubin_max             10296 non-null   float64
 130  h1_bilirubin_min             10296 non-null   float64
 131  h1_bun_max                   25167 non-null   float64
 132  h1_bun_min                   25167 non-null   float64
 133  h1_calcium_max               24236 non-null   float64
 134  h1_calcium_min               24236 non-null   float64
 135  h1_creatinine_max            25373 non-null   float64
 136  h1_creatinine_min            25373 non-null   float64
 137  h1_glucose_max               55084 non-null   float64
 138  h1_glucose_min               55084 non-null   float64
 139  h1_hco3_max                  23762 non-null   float64
 140  h1_hco3_min                  23762 non-null   float64
 141  h1_hemaglobin_max            27367 non-null   float64
 142  h1_hemaglobin_min            27367 non-null   float64
 143  h1_hematocrit_max            27201 non-null   float64
 144  h1_hematocrit_min            27201 non-null   float64
 145  h1_inr_max                   48944 non-null   float64
 146  h1_inr_min                   48944 non-null   float64
 147  h1_lactate_max               11690 non-null   float64
 148  h1_lactate_min               11690 non-null   float64
 149  h1_platelets_max             24428 non-null   float64
 150  h1_platelets_min             24428 non-null   float64
 151  h1_potassium_max             29336 non-null   float64
 152  h1_potassium_min             29336 non-null   float64
 153  h1_sodium_max                28376 non-null   float64
 154  h1_sodium_min                28376 non-null   float64
 155  h1_wbc_max                   24171 non-null   float64
 156  h1_wbc_min                   24171 non-null   float64
 157  d1_arterial_pco2_max         45696 non-null   float64
 158  d1_arterial_pco2_min         45696 non-null   float64
 159  d1_arterial_ph_max           45350 non-null   float64
 160  d1_arterial_ph_min           45350 non-null   float64
 161  d1_arterial_po2_max          46147 non-null   float64
 162  d1_arterial_po2_min          46147 non-null   float64
 163  d1_pao2fio2ratio_max         36818 non-null   float64
 164  d1_pao2fio2ratio_min         36818 non-null   float64
 165  h1_arterial_pco2_max         22491 non-null   float64
 166  h1_arterial_pco2_min         22491 non-null   float64
 167  h1_arterial_ph_max           22308 non-null   float64
 168  h1_arterial_ph_min           22308 non-null   float64
 169  h1_arterial_po2_max          22712 non-null   float64
 170  h1_arterial_po2_min          22712 non-null   float64
 171  h1_pao2fio2ratio_max         16760 non-null   float64
 172  h1_pao2fio2ratio_min         16760 non-null   float64
 173  aids                         130157 non-null  int64
 174  cirrhosis                    130157 non-null  int64
 175  hepatic_failure              130157 non-null  int64
 176  immunosuppression            130157 non-null  int64
 177  leukemia                     130157 non-null  int64
 178  lymphoma                     130157 non-null  int64
 179  solid_tumor_with_metastasis  130157 non-null  int64
 180  diabetes_mellitus            130157 non-null  int64
dtypes: float64(157), int64(18), object(6)
memory usage: 179.7+ MB

<ipython-input-11-4ab921678a25>:1: FutureWarning: null_counts is deprecated. Use show_counts instead
  train.info(verbose=True, null_counts=True)

In [14]:
test.select_dtypes(include='object')

,ethnicity,gender,hospital_admit_source,icu_admit_source,icu_stay_type,icu_type
0,Caucasian,F,Floor,Accident & Emergency,admit,Med-Surg ICU
1,Caucasian,F,Emergency Department,Accident & Emergency,admit,Med-Surg ICU
2,Caucasian,F,Floor,Floor,admit,Med-Surg ICU
3,Caucasian,M,Floor,Floor,admit,Med-Surg ICU
4,Caucasian,M,Direct Admit,Accident & Emergency,admit,Med-Surg ICU
...,...,...,...,...,...,...
10229,Caucasian,F,Floor,Floor,admit,Med-Surg ICU
10230,Caucasian,F,Emergency Department,Accident & Emergency,admit,Med-Surg ICU
10231,Caucasian,F,Step-Down Unit (SDU),Floor,admit,Med-Surg ICU
10232,Caucasian,F,Emergency Department,Accident & Emergency,admit,Med-Surg ICU
10233,Caucasian,M,Emergency Department,Accident & Emergency,admit,Med-Surg ICU

In [35]:
pd.factorize(train['icu_type'].values, sort=True)[1]

array(['CCU-CTICU', 'CSICU', 'CTICU', 'Cardiac ICU', 'MICU',
       'Med-Surg ICU', 'Neuro ICU', 'SICU'], dtype=object)

In [36]:
pd.factorize(test['icu_type'].values, sort=True)[1]

array(['CCU-CTICU', 'CSICU', 'CTICU', 'Cardiac ICU', 'MICU',
       'Med-Surg ICU', 'Neuro ICU', 'SICU'], dtype=object)

In [37]:
train['icu_type'][:10]

0           CTICU
1    Med-Surg ICU
2    Med-Surg ICU
3           CTICU
4    Med-Surg ICU
5    Med-Surg ICU
6    Med-Surg ICU
7    Med-Surg ICU
8       CCU-CTICU
9       CCU-CTICU
Name: icu_type, dtype: object

In [41]:
pd.factorize(train['icu_type'], sort=True)[0][:10]

array([2, 5, 5, 2, 5, 5, 5, 5, 0, 0])

In [39]:
test['icu_type'][:10]

0    Med-Surg ICU
1    Med-Surg ICU
2    Med-Surg ICU
3    Med-Surg ICU
4    Med-Surg ICU
5    Med-Surg ICU
6    Med-Surg ICU
7    Med-Surg ICU
8    Med-Surg ICU
9    Med-Surg ICU
Name: icu_type, dtype: object

In [42]:
pd.factorize(test['icu_type'], sort=True)[0][:10]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [45]:
train.drop('Unnamed: 0', axis=1)

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,h1_pao2fio2ratio_max,h1_pao2fio2ratio_min,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,214826,118,68.0,22.732803,0,Caucasian,M,180.3,Floor,Floor,...,NaN,NaN,0,0,0,0,0,0,0,1
1,246060,81,77.0,27.421875,0,Caucasian,F,160.0,Floor,Floor,...,51.0,51.0,0,0,0,0,0,0,0,1
2,276985,118,25.0,31.952749,0,Caucasian,F,172.7,Emergency Department,Accident & Emergency,...,NaN,NaN,0,0,0,0,0,0,0,0
3,262220,118,81.0,22.635548,1,Caucasian,F,165.1,Operating Room,Operating Room / Recovery,...,337.0,337.0,0,0,0,0,0,0,0,0
4,201746,33,19.0,NaN,0,Caucasian,M,188.0,NaN,Accident & Emergency,...,NaN,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130152,164758,7,50.0,29.287256,0,Caucasian,M,175.3,Emergency Department,Accident & Emergency,...,NaN,NaN,0,0,0,0,0,0,0,0
130153,197653,7,79.0,29.653433,0,Caucasian,F,162.6,Direct Admit,Accident & Emergency,...,NaN,NaN,0,0,0,0,0,0,0,0
130154,219719,7,73.0,32.265371,0,African American,M,177.8,Emergency Department,Accident & Emergency,...,163.0,163.0,0,0,0,0,0,0,0,1
130155,222562,170,81.0,24.408579,0,Caucasian,M,185.4,Emergency Department,Accident & Emergency,...,NaN,NaN,0,0,0,0,0,0,0,0
130156,157942,7,35.0,30.132358,0,African American,M,182.9,Emergency Department,Accident & Emergency,...,NaN,NaN,0,0,0,0,0,0,0,0